issue-104: skipJspc property (4.x branch)
leonardehrenfried/jspc-maven-plugin pull request #108
Opened 2022-12-18 03:51 UTC by knoxg

This PR will allow the plugin to be skipped by specifying `<skipJspc>true</skipJspc>` in the `<configuration>` block, or by supplying `-Djspc.skip` on the commandline.

2022-12-19 08:43 UTC, leonardehrenfried commented on src/main/java/io/leonard/maven/plugins/jspc/JspcMojo.java
> +  private boolean skipJspc;
```suggestion
  private boolean skip;
```

I think we can leave out the jspc part which you can derive form the context.

2022-12-19 08:43 UTC, leonardehrenfried requested changes
This looks good but we can leave out the jsp part from the variable name.

Thanks for the PR!

2022-12-19 23:57 UTC, knoxg commented on src/main/java/io/leonard/maven/plugins/jspc/JspcMojo.java
> +  private boolean skipJspc;
yep ok will update

2022-12-20 07:51 UTC, knoxg commented
ok have made the suggested changes above ( and to the other PR if we end up creating a 3.x branch )

2022-12-20 07:52 UTC, knoxg commented on src/main/java/io/leonard/maven/plugins/jspc/JspcMojo.java
> +  private boolean skipJspc;
done

2022-12-20 07:52 UTC, knoxg commented on src/main/java/io/leonard/maven/plugins/jspc/JspcMojo.java
> +    if ( skipJspc ) {
done

2022-12-20 08:26 UTC, leonardehrenfried approved these changes

2022-12-20 08:26 UTC, merged

2022-12-20 08:51 UTC, leonardehrenfried commented
This code has been released as version 4.0.1. Give it a few minutes to show up on Maven Central: https://repo1.maven.org/maven2/io/leonard/maven/plugins/jspc-maven-plugin/